name: VS Code Extension Release

on:
  release:
    types: [published]

jobs:
  release:
    if: startsWith(github.ref_name, 'vscode-v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

      - name: Upload VSIX to Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
